# Generated by Django 5.2.4 on 2025-08-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="flashcards_app.collection",
            ),
        ),
    ]
