# Generated by Django 5.2.4 on 2025-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards_app", "0003_add_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="back",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="front",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deck",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
